import React from 'react';

export const meta = {
  title: 'Count and Say',
  category: 'Strings',
  difficulty: 'Medium',
  timeComplexity: 'O(2^N)',
  spaceComplexity: 'O(2^N)',
  description: 'Generates the nth term of the Count-and-Say sequence using iterative run-length encoding on the previous term string.'
};

export const solutions = {
  cpp: `// C++ Count and Say
// Time: O(2^N) | Space: O(2^N)
#include <string>
using namespace std;

class Solution {
public:
    string countAndSay(int n) {
        if (n == 1) return "1";

        string s = "1";
        for (int step = 2; step <= n; step++) {
            string nextStr = "";
            int i = 0;
            while (i < s.size()) {
                int count = 1;
                while (i + 1 < s.size() && s[i] == s[i + 1]) {
                    count++;
                    i++;
                }
                nextStr += to_string(count) + s[i];
                i++;
            }
            s = nextStr;
        }
        return s;
    }
};`,
  python: `# Python 3 Count and Say
# Time: O(2^N) | Space: O(2^N)
class Solution:
    def countAndSay(self, n: int) -> str:
        if n == 1:
            return "1"

        s = "1"
        for _ in range(2, n + 1):
            next_str = []
            i = 0
            while i < len(s):
                count = 1
                while i + 1 < len(s) and s[i] == s[i + 1]:
                    count += 1
                    i += 1
                next_str.append(f"{count}{s[i]}")
                i += 1
            s = "".join(next_str)

        return s`,
  java: `// Java Count and Say
// Time: O(2^N) | Space: O(2^N)
class Solution {
    public String countAndSay(int n) {
        if (n == 1) return "1";

        String s = "1";
        for (int step = 2; step <= n; step++) {
            StringBuilder sb = new StringBuilder();
            int i = 0;
            while (i < s.length()) {
                int count = 1;
                while (i + 1 < s.length() && s.charAt(i) == s.charAt(i + 1)) {
                    count++;
                    i++;
                }
                sb.append(count).append(s.charAt(i));
                i++;
            }
            s = sb.toString();
        }
        return s;
    }
}`,
  javascript: `// JavaScript Count and Say
// Time: O(2^N) | Space: O(2^N)
var countAndSay = function(n) {
    if (n === 1) return "1";

    let s = "1";
    for (let step = 2; step <= n; step++) {
        let nextStr = "";
        let i = 0;
        while (i < s.length) {
            let count = 1;
            while (i + 1 < s.length && s[i] === s[i + 1]) {
                count++;
                i++;
            }
            nextStr += count + s[i];
            i++;
        }
        s = nextStr;
    }
    return s;
};`
};

export const steps = [
  {
    title: '1. Base Term: n = 1 -> "1"',
    phase: 'STEP_1',
    codeLine: 10,
    termIndex: 1,
    currentTerm: '1',
    groups: [{ count: 1, char: '1' }],
    variables: { n: 1, result: '"1"' },
    explain: 'Base case of the sequence: countAndSay(1) is defined as "1".',
    intuition: 'Every subsequent term is generated by describing the frequency of consecutive identical digits in the preceding term.'
  },
  {
    title: '2. Generate n = 2: "1" has one 1 -> "11"',
    phase: 'STEP_2',
    codeLine: 18,
    termIndex: 2,
    currentTerm: '11',
    groups: [{ count: 1, char: '1' }],
    variables: { previous: '"1"', description: 'one "1"', next: '"11"' },
    explain: 'Reading "1": there is one "1" -> "11".',
    intuition: 'Run-length encoding transforms count + character.'
  },
  {
    title: '3. Generate n = 3: "11" has two 1s -> "21"',
    phase: 'STEP_3',
    codeLine: 18,
    termIndex: 3,
    currentTerm: '21',
    groups: [{ count: 2, char: '1' }],
    variables: { previous: '"11"', description: 'two "1"s', next: '"21"' },
    explain: 'Reading "11": there are two consecutive "1"s -> "21".',
    intuition: 'Consecutive matching characters merge into a single count prefix.'
  },
  {
    title: '4. Generate n = 4 & 5: "21" -> "1211" -> "111221"',
    phase: 'COMPLETED',
    codeLine: 24,
    termIndex: 5,
    currentTerm: '111221',
    groups: [
      { count: 1, char: '2' },
      { count: 1, char: '1' }
    ],
    variables: { 'n=4': '"1211"', 'n=5': '"111221"', description: 'three 1s, two 2s, one 1' },
    explain: 'For n = 4 ("1211"): one 1 ("11"), one 2 ("12"), two 1s ("21") -> "111221".',
    intuition: 'The sequence progressively grows according to run-length descriptions.'
  }
];

export default function CountAndSayVisualizer({ currentStep = 0 }) {
  const step = steps[Math.min(currentStep, steps.length - 1)] || steps[0];

  return (
    <div className="w-full max-w-2xl mx-auto flex flex-col items-center justify-center p-6 space-y-6">
      {/* Badges */}
      <div className="flex flex-wrap items-center justify-center gap-3 text-xs font-mono">
        <span className="px-3 py-1.5 rounded-xl bg-purple-500/15 border border-purple-500/30 text-purple-300 font-semibold">
          Term Index (n): {step.termIndex}
        </span>
        <span className="px-3 py-1.5 rounded-xl bg-emerald-500/15 border border-emerald-500/30 text-emerald-300 font-bold">
          Term String: "{step.currentTerm}"
        </span>
      </div>

      {/* String Digits Visualization */}
      <div className="w-full bg-[#12131b] border border-[#272b3c] rounded-2xl p-6 flex flex-col items-center gap-4 shadow-xl">
        <span className="text-xs font-mono text-[#8a8ea3] uppercase tracking-wider">
          Sequence Term Representation
        </span>

        <div className="flex items-center justify-center gap-2 py-3 font-mono">
          {step.currentTerm.split('').map((char, idx) => (
            <div
              key={idx}
              className="w-12 h-14 rounded-xl border border-cyan-500/40 bg-cyan-500/10 flex flex-col items-center justify-center text-cyan-300"
            >
              <span className="text-[9px] text-[#8a8ea3]">[{idx}]</span>
              <span className="text-lg font-bold text-amber-300">{char}</span>
            </div>
          ))}
        </div>

        {/* Group Descriptions */}
        <div className="w-full border-t border-[#272b3c] pt-3 flex flex-col items-center gap-2">
          <span className="text-[11px] font-mono text-purple-300">
            Run-Length Groupings:
          </span>
          <div className="flex flex-wrap items-center justify-center gap-2 font-mono text-xs">
            {step.groups.map((g, i) => (
              <span
                key={i}
                className="px-3 py-1.5 rounded-lg bg-[#161824] border border-[#272b3c] text-emerald-300"
              >
                {g.count} &times; '{g.char}' &rarr; "{g.count}{g.char}"
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Explanation */}
      <div className="w-full bg-[#161824] border border-[#272b3c] rounded-xl p-3 text-xs font-mono text-center text-[#8a8ea3]">
        {step.explain}
      </div>
    </div>
  );
}
